version: '3.8'

services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" # Mapea el puerto 27017 al host
    volumes:
      - mongodb_data:/data/db # Persistencia de datos
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
